# Generated by Django 4.0.4 on 2022-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='etablisment',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='site_web',
            field=models.URLField(blank=True),
        ),
    ]
