# Generated by Django 4.0.4 on 2022-05-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_division_site_web_equipe_site_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='affecte',
            field=models.BooleanField(default=False),
        ),
    ]
