# Generated by Django 4.0.4 on 2022-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_alter_researcher_linkedin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='linkedin_account',
            field=models.URLField(blank=True),
        ),
    ]
