# Generated by Django 4.0.4 on 2022-05-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_alter_researcher_linkedin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='twitter_account',
        ),
    ]
