# Generated by Django 4.0.4 on 2022-05-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_remove_researcher_twitter_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='role',
            field=models.CharField(choices=[("Membre d'equipe ", "Membre d'equipe "), ("Chef d'equipe", "Chef d'equipe"), ('Chef de Laboratoire', 'Chef de Laboratoire'), ('Chef de Divsion', 'Chef de Division'), ("Chef d'etablisment", "Chef d'etablisment")], max_length=100, null=True),
        ),
    ]
