# Generated by Django 4.0.4 on 2022-05-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_researcher_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='id',
            new_name='idw',
        ),
    ]
