# Generated by Django 4.0.4 on 2022-05-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_rename_id_location_idw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='idw',
            new_name='id',
        ),
    ]
