# Generated by Django 4.0.4 on 2022-05-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_rename_idw_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
