# Generated by Django 4.0.4 on 2022-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_alter_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, default='D', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, "Chef d'etablisment"), (2, 'Chef de Division'), (3, 'Chef de Laboratoire'), (4, "Chef d'equipe"), (5, "Membre d'equipe ")], null=True),
        ),
    ]
