# Generated by Django 4.0.4 on 2022-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_alter_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, default='D', upload_to='images'),
        ),
    ]
