# Generated by Django 4.0.4 on 2022-05-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_alter_researcher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='laboratoire',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='role',
        ),
        migrations.AddField(
            model_name='equipe',
            name='divsion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.division'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, default='D', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Laboratoire',
        ),
    ]
