# Generated by Django 4.0.4 on 2022-05-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_alter_researcher_image_alter_researcher_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='role',
            new_name='researcher_role',
        ),
    ]
