# Generated by Django 4.0.4 on 2022-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_rename_role_researcher_researcher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='researcher_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, "Chef d'etablisment"), (2, 'Chef de Division'), (3, 'Chef de Laboratoire'), (4, "Chef d'equipe"), (5, "Membre d'equipe")], default=1, null=True),
        ),
    ]
